#!/bin/bash

ROOT_DIR="./src"

generate_indices() {
  local dir="$1"
  local index_file="$dir/index.ts"

  local ts_files
  ts_files=$(find "$dir" -maxdepth 1 -type f -name "*.ts" ! -name "index.ts")
  if [[ -z "$ts_files" ]]; then
    return
  fi

  echo "Generating index.ts for $dir"

  echo "/* Auto-generated by $(basename "$(test -L "$0" && readlink "$0" || echo "$0")") */" > "$index_file"
  for file in $ts_files; do
    local module_name
    module_name=$(basename "$file" .ts)
    echo "export * from \"./$module_name.js\";" >> "$index_file"
  done

  for subdir in "$dir"/*; do
    if [[ ! -d "$subdir" ]]; then
      continue
    fi

    generate_indices "$subdir"
  done

  if [[ "$(realpath "$dir")" == "$(realpath "$ROOT_DIR")" ]]; then
    return
  fi

  local parent_dir
  parent_dir=$(dirname "$dir")
  local parent_index_file="$parent_dir/index.ts"
  local module_name
  module_name=$(basename "$dir")
  echo "export * from \"./$module_name/index.js\";" >> "$parent_index_file"
}

if [[ ! -d "$ROOT_DIR" ]]; then
  echo "Root directory ‘$ROOT_DIR’ not found."
  exit 1
fi

generate_indices "$ROOT_DIR"

echo "Index files generated successfully."
