import {Request} from "../Request.js";
import {Response} from "../response/Response.js";
import {Route} from "./Route.js";

/**
 * A registry that manages multiple routes and delegates request handling.
 */
class RouteRegistry implements Route {
    private readonly routes = new Set<Route>();

    /**
     * Registers one or more routes into the registry.
     *
     * @param routes The routes to register.
     */
    public register(...routes: Route[]) {
        for (const route of routes)
            this.routes.add(route);
    }

    /**
     * Check if any registered route matches the given request.
     * @param req The request to check.
     */
    public match(req: Request): boolean {
        for (const route of this.routes)
            if (route.match(req))
                return true;
        return false;
    }

    /**
     * Find and invoke the first matching route to handle the request.
     * @param req The request to handle.
     * @return The response generated by handling the request.
     * @throws {@link RouteRegistry.NoRouteError} If no route matches the request.
     */
    public handle(req: Request): Response | Promise<Response> {
        for (const route of this.routes)
            if (route.match(req))
                return route.handle(req);
        throw new RouteRegistry.NoRouteError();
    }
}

namespace RouteRegistry {
    /**
     * No route can be found for handling the request.
     */
    export class NoRouteError extends Error {
        public constructor() {
            super("No route in this registry matches the request.");
        }
    }
}

export {RouteRegistry};
