name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  ts-modified:
    name: TS files changed
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    outputs:
      ts_modified: ${{ steps.check-files.outputs.ts_modified }}
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 2

      - name: Check for modified .ts files
        id: check-files
        run: |
          if git show --name-only --pretty="" ${{ github.event.pull_request.head.sha }} | grep -E "\.ts$"; then
            echo "ts_modified=true" >> $GITHUB_OUTPUT
          else
            echo "ts_modified=false" >> $GITHUB_OUTPUT
          fi

  update-indices:
    name: Update indices
    needs: ts-modified
    if: needs.ts-modified.outputs.ts_modified == 'true'
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.check_changes.outputs.has_changes }}
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.BOT_GH_TOKEN }}

      - name: Generate indices
        run: ./generateIndices.sh

      - name: Check uncommitted indices
        id: check_changes
        run: |
          echo "has_changes=$([ -n "$(git diff --name-only HEAD "**/index.ts")" ] && echo "true" || echo "false")" >> $GITHUB_OUTPUT

      - name: Commit indices
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          echo "${{ secrets.BOT_PGP_KEY }}" | gpg --import --batch
          git config --global user.name "Cloudnode [bot]"
          git config --global user.email "203399718+cloudnode-bot@users.noreply.github.com"
          git config --global user.signingkey "203399718+cloudnode-bot@users.noreply.github.com"
          git add "**/index.ts"
          git commit -S -m "chore: update indices"
          git push

  build:
    name: Build
    needs: update-indices
    if: always() && (needs.update-indices.result == 'skipped' || needs.update-indices.outputs.has_changes == 'false')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
          cache: npm

      - name: Install latest NPM
        run: npm i -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Pack
        run: npm pack

      - name: Upload package artifact
        uses: actions/upload-artifact@v5
        with:
          name: package
          path: cldn-web-ts-0.0.0-dev.tgz
  publish:
    name: Publish
    needs: build
    if: always() && github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
          cache: npm

      - name: Install latest NPM
        run: npm i -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Download build artifact
        uses: actions/download-artifact@v5
        with:
          name: package
          path: ./package

      - name: Extract build package
        working-directory: ./package
        run: tar -xzf cldn-web-ts-0.0.0-dev.tgz

      - name: Set version from release tag
        run: npm version ${{ github.event.release.tag_name }} --git-tag-version=false

      - name: Copy package.json to build package
        run: |-
          cp package.json package/package
          cp package.json package/package/dist

      - name: Publish release to NPM
        if: "!github.event.release.prerelease"
        working-directory: ./package/package
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Publish release candidate to NPM
        if: github.event.release.prerelease
        working-directory: ./package/package
        run: npm publish --provenance --access public --tag rc
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Generate docs
        if: "!github.event.release.prerelease"
        run: npm run docs

      - name: Set up GitHub pages
        if: "!github.event.release.prerelease"
        uses: actions/configure-pages@v5

      - name: Upload docs artifact to pages
        if: "!github.event.release.prerelease"
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        if: "!github.event.release.prerelease"
        id: deployment
        uses: actions/deploy-pages@v4
